config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :scores

      resources :families

      resources :user_types

      resources :agenda_items

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "agenda_items#index"
  resources :scores
  resources :families
  resources :user_types
  resources :agenda_items
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/agenda_item.rb
require "open-uri"
class AgendaItem < ApplicationRecord
  before_validation :geocode_location

  def geocode_location
    if location.present?
      url = "https://maps.googleapis.com/maps/api/geocode/json?key=#{ENV['GMAP_API_KEY']}&address=#{URI.encode(location)}"

      raw_data = open(url).read

      parsed_data = JSON.parse(raw_data)

      if parsed_data["results"].present?
        self.location_latitude = parsed_data["results"][0]["geometry"]["location"]["lat"]

        self.location_longitude = parsed_data["results"][0]["geometry"]["location"]["lng"]

        self.location_formatted_address = parsed_data["results"][0]["formatted_address"]
      end
    end
  end
  mount_base64_uploader :photo, PhotoUploader

  # Direct associations

  belongs_to :leader,
             class_name: "User"

  # Indirect associations

  # Validations

  validates :activity, presence: true

  validates :description, presence: true

  validates :end_time, presence: true

  validates :is_cyoa, presence: true

  validates :leader_id, presence: true

  validates :location, presence: true

  validates :start_time, presence: true

  # Scopes

  def to_s
    start_time
  end
end

app/controllers/agenda_items_controller.rb
class AgendaItemsController < ApplicationController
  before_action :set_agenda_item, only: %i[show edit update destroy]

  def index
    @q = AgendaItem.ransack(params[:q])
    @agenda_items = @q.result(distinct: true).includes(:leader).page(params[:page]).per(10)
    @location_hash = Gmaps4rails.build_markers(@agenda_items.where.not(location_latitude: nil)) do |agenda_item, marker|
      marker.lat agenda_item.location_latitude
      marker.lng agenda_item.location_longitude
    end
  end

  def show; end

  def new
    @agenda_item = AgendaItem.new
  end

  def edit; end

  def create
    @agenda_item = AgendaItem.new(agenda_item_params)

    if @agenda_item.save
      message = "AgendaItem was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @agenda_item, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @agenda_item.update(agenda_item_params)
      redirect_to @agenda_item, notice: "Agenda item was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @agenda_item.destroy
    message = "AgendaItem was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to agenda_items_url, notice: message
    end
  end

  private

  def set_agenda_item
    @agenda_item = AgendaItem.find(params[:id])
  end

  def agenda_item_params
    params.require(:agenda_item).permit(:start_time, :end_time, :location,
                                        :activity, :description, :photo, :leader_id, :is_cyoa)
  end
end

app/controllers/api/v1/agenda_items_controller.rb
class Api::V1::AgendaItemsController < Api::V1::GraphitiController
  def index
    agenda_items = AgendaItemResource.all(params)
    respond_with(agenda_items)
  end

  def show
    agenda_item = AgendaItemResource.find(params)
    respond_with(agenda_item)
  end

  def create
    agenda_item = AgendaItemResource.build(params)

    if agenda_item.save
      render jsonapi: agenda_item, status: :created
    else
      render jsonapi_errors: agenda_item
    end
  end

  def update
    agenda_item = AgendaItemResource.find(params)

    if agenda_item.update_attributes
      render jsonapi: agenda_item
    else
      render jsonapi_errors: agenda_item
    end
  end

  def destroy
    agenda_item = AgendaItemResource.find(params)

    if agenda_item.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: agenda_item
    end
  end
end

app/views/agenda_items/_agenda_items_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "agenda_items_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :start_time, "Start time" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='start_timegteqPicker' data-target-input="nearest">
          <%= f.text_field :start_time_gteq, :class => "form-control datetimepicker-input", :placeholder => "Start time greater than or equal to", :data => {:target => '#start_timegteqPicker'} %>
          <div class="input-group-append" data-target='#start_timegteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='start_timelteqPicker' data-target-input="nearest">
          <%= f.text_field :start_time_lteq, :class => "form-control datetimepicker-input", :placeholder => "Start time less than or equal to", :data => {:target => '#start_timelteqPicker'} %>
          <div class="input-group-append" data-target='#start_timelteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#start_timegteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#start_timelteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#start_timegteqPicker').on("dp.change", function (e) {
              $('#start_timelteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#start_timelteqPicker').on("dp.change", function (e) {
              $('#start_timegteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :is_cyoa_cont, "Is cyoa contains" %>
    <%= f.text_field :is_cyoa_cont, :class => "form-control", :placeholder => "Is cyoa contains" %>
  </div>

  <div class="form-group">
    <%= f.label :description_cont, "Description contains" %>
    <%= f.text_field :description_cont, :class => "form-control", :placeholder => "Description contains" %>
  </div>

  <div class="form-group">
    <%= f.label :activity_cont, "Activity contains" %>
    <%= f.text_field :activity_cont, :class => "form-control", :placeholder => "Activity contains" %>
  </div>

  <div class="form-group">
    <%= f.label :end_time, "End time" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='end_timegteqPicker' data-target-input="nearest">
          <%= f.text_field :end_time_gteq, :class => "form-control datetimepicker-input", :placeholder => "End time greater than or equal to", :data => {:target => '#end_timegteqPicker'} %>
          <div class="input-group-append" data-target='#end_timegteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='end_timelteqPicker' data-target-input="nearest">
          <%= f.text_field :end_time_lteq, :class => "form-control datetimepicker-input", :placeholder => "End time less than or equal to", :data => {:target => '#end_timelteqPicker'} %>
          <div class="input-group-append" data-target='#end_timelteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#end_timegteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#end_timelteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#end_timegteqPicker').on("dp.change", function (e) {
              $('#end_timelteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#end_timelteqPicker').on("dp.change", function (e) {
              $('#end_timegteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :created_at, "User Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='leadergteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :leader_created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "User Created at greater than or equal to", :data => {:target => '#leadergteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#leadergteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='leaderlteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :leader_created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "User Created at less than or equal to", :data => {:target => '#leaderlteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#leaderlteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#leadergteqcreated_atPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#leaderlteqcreated_atPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#leadergteqcreated_atPicker').on("dp.change", function (e) {
              $('#leaderlteqcreated_atPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#leaderlteqcreated_atPicker').on("dp.change", function (e) {
              $('#leadergteqcreated_atPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/agenda_items" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#agenda_items_filters">
  Show filters
</a>

app/views/agenda_items/_all_photos_map.html.erb
<div id="location_map" style="height: 480px;"></div>
<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'location_map'}}, function(){
    markers = handler.addMarkers(<%= raw @location_hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/agenda_items/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Agenda Item #<%= agenda_item.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Start time</dt>
      <dd><%= agenda_item.start_time %></dd>

      <dt>End time</dt>
      <dd><%= agenda_item.end_time %></dd>

      <dt>Location</dt>
      <dd>
        <div>
          <%= render partial: "agenda_items/one_photo_map" %>
        </div>
      </dd>

      <dt>Activity</dt>
      <dd><%= agenda_item.activity %></dd>

      <dt>Description</dt>
      <dd><%= agenda_item.description %></dd>

      <dt>Photo</dt>
      <dd>
        <%= cl_image_tag @agenda_item.photo, class: "img-fluid" %>
      </dd>

      <dt>Leader</dt>
      <dd>
        <% if @agenda_item.leader.present? %>
          <%= link_to agenda_item.leader, agenda_item.leader %>
        <% end %>
      </dd>

      <dt>Is cyoa</dt>
      <dd><%= agenda_item.is_cyoa %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back agenda_item, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_agenda_item_url(agenda_item), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to agenda_item, method: :delete, data: { confirm: "Do you really want to delete this agenda_item?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(agenda_item.updated_at) %> ago
  </div>
</div>

app/views/agenda_items/_form.html.erb
<% was_validated = agenda_item.errors.any? %>

<%= form_with(model: agenda_item, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% start_time_class = "form-control" %>
    <% start_time_was_invalid = agenda_item.errors.include?(:start_time) %>

    <% if was_validated %>
      <% if start_time_was_invalid %>
        <% start_time_class << " is-invalid" %>
      <% else %>
        <% start_time_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :start_time %>
    <%= f.datetime_select :start_time, class: start_time_class, placeholder: "Enter start time" %>
    <% if start_time_was_invalid %>
      <% agenda_item.errors.full_messages_for(:start_time).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% end_time_class = "form-control" %>
    <% end_time_was_invalid = agenda_item.errors.include?(:end_time) %>

    <% if was_validated %>
      <% if end_time_was_invalid %>
        <% end_time_class << " is-invalid" %>
      <% else %>
        <% end_time_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :end_time %>
    <%= f.datetime_select :end_time, class: end_time_class, placeholder: "Enter end time" %>
    <% if end_time_was_invalid %>
      <% agenda_item.errors.full_messages_for(:end_time).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% location_class = "form-control" %>
    <% location_was_invalid = agenda_item.errors.include?(:location) %>

    <% if was_validated %>
      <% if location_was_invalid %>
        <% location_class << " is-invalid" %>
      <% else %>
        <% location_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :location %>
    <%= f.text_field :location, class: location_class, placeholder: "Enter location" %>
    <% if location_was_invalid %>
      <% agenda_item.errors.full_messages_for(:location).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% activity_class = "form-control" %>
    <% activity_was_invalid = agenda_item.errors.include?(:activity) %>

    <% if was_validated %>
      <% if activity_was_invalid %>
        <% activity_class << " is-invalid" %>
      <% else %>
        <% activity_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :activity %>
    <%= f.text_field :activity, class: activity_class, placeholder: "Enter activity" %>
    <% if activity_was_invalid %>
      <% agenda_item.errors.full_messages_for(:activity).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% description_class = "form-control" %>
    <% description_was_invalid = agenda_item.errors.include?(:description) %>

    <% if was_validated %>
      <% if description_was_invalid %>
        <% description_class << " is-invalid" %>
      <% else %>
        <% description_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :description %>
    <%= f.text_area :description, class: description_class, placeholder: "Enter description" %>
    <% if description_was_invalid %>
      <% agenda_item.errors.full_messages_for(:description).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% photo_class = "form-control" %>
    <% photo_was_invalid = agenda_item.errors.include?(:photo) %>

    <% if was_validated %>
      <% if photo_was_invalid %>
        <% photo_class << " is-invalid" %>
      <% else %>
        <% photo_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :photo %>
    <%= f.file_field :photo, class: "form-control" %>
    <% if photo_was_invalid %>
      <% agenda_item.errors.full_messages_for(:photo).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% leader_class = "form-control" %>
    <% leader_was_invalid = agenda_item.errors.include?(:leader) %>

    <% if was_validated %>
      <% if leader_was_invalid %>
        <% leader_class << " is-invalid" %>
      <% else %>
        <% leader_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :leader_id %>
    <%= f.collection_select :leader_id, User.all, :id, :to_s, {}, class: "form-control" %>
    <% if leader_was_invalid %>
      <% agenda_item.errors.full_messages_for(:leader).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% is_cyoa_class = "form-control" %>
    <% is_cyoa_was_invalid = agenda_item.errors.include?(:is_cyoa) %>

    <% if was_validated %>
      <% if is_cyoa_was_invalid %>
        <% is_cyoa_class << " is-invalid" %>
      <% else %>
        <% is_cyoa_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :is_cyoa %>
    <%= f.text_field :is_cyoa, class: is_cyoa_class, placeholder: "Enter is cyoa" %>
    <% if is_cyoa_was_invalid %>
      <% agenda_item.errors.full_messages_for(:is_cyoa).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/agenda_items/_list_item.html.erb
<%= link_to agenda_item, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= agenda_item %>
    <small class="text-muted">
      <%= time_ago_in_words(agenda_item.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/agenda_items/_one_photo_map.html.erb
<div id="location_map" style="height: 480px;"></div>

<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'location_map'}}, function(){
    markers = handler.addMarkers([
      {
        "lat": <%= @agenda_item.location_latitude %>,
        "lng": <%= @agenda_item.location_longitude %>,
        "infowindow": "<h5><%= @agenda_item.created_at %></h5><small><%= @agenda_item.location_formatted_address %></small>"
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/agenda_items/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Agenda Item #<%= @agenda_item.id %>
      </h2>

      <div class="card-body">
        <%= render "form", agenda_item: @agenda_item %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/agenda_items/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Agenda Items

      <%= link_to new_agenda_item_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "agenda_items/agenda_items_search_form" %>
  </div>
</div>

<div class="row mb-3">
  <div class="col-md-12">
    <%= render partial: "agenda_items/all_photos_map" %>
  </div>
</div>


<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Agenda Items

        <%= link_to new_agenda_item_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @agenda_items, partial: "list_item", as: :agenda_item %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @agenda_items, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/agenda_items/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Agenda Item
      </h2>

      <div class="card-body">
        <%= render "form", agenda_item: @agenda_item %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/agenda_items/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @agenda_item, partial: "card", as: :agenda_item %>
  </div>
</div>