config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :scores

      resources :families

      resources :user_types

      resources :agenda_items

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "agenda_items#index"
  resources :scores
  resources :families
  resources :user_types
  resources :agenda_items
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/score.rb
class Score < ApplicationRecord
  # Direct associations

  belongs_to :family

  # Indirect associations

  # Validations

  validates :dsecription, presence: true

  validates :family_id, presence: true

  validates :score, presence: true

  # Scopes

  def to_s
    family.to_s
  end
end

app/controllers/api/v1/scores_controller.rb
class Api::V1::ScoresController < Api::V1::GraphitiController
  def index
    scores = ScoreResource.all(params)
    respond_with(scores)
  end

  def show
    score = ScoreResource.find(params)
    respond_with(score)
  end

  def create
    score = ScoreResource.build(params)

    if score.save
      render jsonapi: score, status: :created
    else
      render jsonapi_errors: score
    end
  end

  def update
    score = ScoreResource.find(params)

    if score.update_attributes
      render jsonapi: score
    else
      render jsonapi_errors: score
    end
  end

  def destroy
    score = ScoreResource.find(params)

    if score.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: score
    end
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: %i[show edit update destroy]

  def index
    @q = Score.ransack(params[:q])
    @scores = @q.result(distinct: true).includes(:family).page(params[:page]).per(10)
  end

  def show; end

  def new
    @score = Score.new
  end

  def edit; end

  def create
    @score = Score.new(score_params)

    if @score.save
      message = "Score was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @score, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @score.update(score_params)
      redirect_to @score, notice: "Score was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @score.destroy
    message = "Score was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to scores_url, notice: message
    end
  end

  private

  def set_score
    @score = Score.find(params[:id])
  end

  def score_params
    params.require(:score).permit(:family_id, :score, :dsecription)
  end
end

app/views/scores/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Score #<%= score.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Family</dt>
      <dd>
        <% if @score.family.present? %>
          <%= link_to score.family, score.family %>
        <% end %>
      </dd>

      <dt>Score</dt>
      <dd><%= score.score %></dd>

      <dt>Dsecription</dt>
      <dd><%= score.dsecription %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back score, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_score_url(score), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to score, method: :delete, data: { confirm: "Do you really want to delete this score?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(score.updated_at) %> ago
  </div>
</div>

app/views/scores/_form.html.erb
<% was_validated = score.errors.any? %>

<%= form_with(model: score, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% family_class = "form-control" %>
    <% family_was_invalid = score.errors.include?(:family) %>

    <% if was_validated %>
      <% if family_was_invalid %>
        <% family_class << " is-invalid" %>
      <% else %>
        <% family_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :family_id %>
    <%= f.collection_select :family_id, Family.all, :id, :to_s, {}, class: "form-control" %>
    <% if family_was_invalid %>
      <% score.errors.full_messages_for(:family).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% score_class = "form-control" %>
    <% score_was_invalid = score.errors.include?(:score) %>

    <% if was_validated %>
      <% if score_was_invalid %>
        <% score_class << " is-invalid" %>
      <% else %>
        <% score_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :score %>
    <%= f.number_field :score, class: score_class, placeholder: "Enter score" %>
    <% if score_was_invalid %>
      <% score.errors.full_messages_for(:score).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% dsecription_class = "form-control" %>
    <% dsecription_was_invalid = score.errors.include?(:dsecription) %>

    <% if was_validated %>
      <% if dsecription_was_invalid %>
        <% dsecription_class << " is-invalid" %>
      <% else %>
        <% dsecription_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :dsecription %>
    <%= f.text_area :dsecription, class: dsecription_class, placeholder: "Enter dsecription" %>
    <% if dsecription_was_invalid %>
      <% score.errors.full_messages_for(:dsecription).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/scores/_list_item.html.erb
<%= link_to score, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= score %>
    <small class="text-muted">
      <%= time_ago_in_words(score.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/scores/_scores_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "scores_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :dsecription_cont, "Dsecription contains" %>
    <%= f.text_field :dsecription_cont, :class => "form-control", :placeholder => "Dsecription contains" %>
  </div>

  <div class="form-group">
    <%= f.label :score, "Score" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :score_gteq, :class => "form-control", :placeholder => "Score greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :score_lteq, :class => "form-control", :placeholder => "Score less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :family_name_cont, "Family name contains" %>
    <%= f.text_field :family_name_cont, :class => "form-control", :placeholder => "Family name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/scores" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#scores_filters">
  Show filters
</a>

app/views/scores/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Score #<%= @score.id %>
      </h2>

      <div class="card-body">
        <%= render "form", score: @score %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/scores/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Scores

      <%= link_to new_score_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "scores/scores_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Scores

        <%= link_to new_score_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @scores, partial: "list_item", as: :score %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @scores, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/scores/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Score
      </h2>

      <div class="card-body">
        <%= render "form", score: @score %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/scores/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @score, partial: "card", as: :score %>
  </div>
</div>