config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :scores

      resources :families

      resources :user_types

      resources :agenda_items

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "agenda_items#index"
  resources :scores
  resources :families
  resources :user_types
  resources :agenda_items
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/family.rb
class Family < ApplicationRecord
  mount_base64_uploader :crest, CrestUploader

  # Direct associations

  has_many   :users,
             dependent: :destroy

  has_many   :scores,
             dependent: :destroy

  # Indirect associations

  # Validations

  validates :name, presence: true

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/families_controller.rb
class Api::V1::FamiliesController < Api::V1::GraphitiController
  def index
    families = FamilyResource.all(params)
    respond_with(families)
  end

  def show
    family = FamilyResource.find(params)
    respond_with(family)
  end

  def create
    family = FamilyResource.build(params)

    if family.save
      render jsonapi: family, status: :created
    else
      render jsonapi_errors: family
    end
  end

  def update
    family = FamilyResource.find(params)

    if family.update_attributes
      render jsonapi: family
    else
      render jsonapi_errors: family
    end
  end

  def destroy
    family = FamilyResource.find(params)

    if family.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: family
    end
  end
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: %i[show edit update destroy]

  def index
    @q = Family.ransack(params[:q])
    @families = @q.result(distinct: true).includes(:scores,
                                                   :users).page(params[:page]).per(10)
  end

  def show
    @user = User.new
    @score = Score.new
  end

  def new
    @family = Family.new
  end

  def edit; end

  def create
    @family = Family.new(family_params)

    if @family.save
      redirect_to @family, notice: "Family was successfully created."
    else
      render :new
    end
  end

  def update
    if @family.update(family_params)
      redirect_to @family, notice: "Family was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @family.destroy
    redirect_to families_url, notice: "Family was successfully destroyed."
  end

  private

  def set_family
    @family = Family.find(params[:id])
  end

  def family_params
    params.require(:family).permit(:name, :crest, :motto)
  end
end

app/views/families/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Family #<%= family.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= family.name %></dd>

      <dt>Crest</dt>
      <dd>
        <%= cl_image_tag @family.crest, class: "img-fluid" %>
      </dd>

      <dt>Motto</dt>
      <dd><%= family.motto %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back family, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_family_url(family), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to family, method: :delete, data: { confirm: "Do you really want to delete this family?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(family.updated_at) %> ago
  </div>
</div>

app/views/families/_families_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "families_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :motto_cont, "Motto contains" %>
    <%= f.text_field :motto_cont, :class => "form-control", :placeholder => "Motto contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :created_at, "User Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='usersgteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :users_created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "User Created at greater than or equal to", :data => {:target => '#usersgteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#usersgteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='userslteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :users_created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "User Created at less than or equal to", :data => {:target => '#userslteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#userslteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#usersgteqcreated_atPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#userslteqcreated_atPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#usersgteqcreated_atPicker').on("dp.change", function (e) {
              $('#userslteqcreated_atPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#userslteqcreated_atPicker').on("dp.change", function (e) {
              $('#usersgteqcreated_atPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/families" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#families_filters">
  Show filters
</a>

app/views/families/_family_scores.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Scores

    <a data-toggle="collapse" href="#family_scores_new_form">
      Add score
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @family.scores.each do |score| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to score, score %>

        <%= link_to score, method: :delete, data: { confirm: "Do you really want to delete this score" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="family_scores_new_form">
        <%= render partial: "families/family_scores_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/families/_family_scores_new_form.html.erb
<%= form_with(model: @score, local: true) do |f| %>

  <%= f.hidden_field :family_id, value: @family.id %>

  <div class="form-group">
    <%= f.label :score %>

    <%= f.text_field :score, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :dsecription %>
    <%= f.text_area :dsecription, rows: "3", class: "form-control" %>
  </div>

  <%= f.submit "Create score", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/families/_family_users.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Users

    <a data-toggle="collapse" href="#family_users_new_form">
      Add user
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @family.users.each do |user| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to user, user %>

        <%= link_to user, method: :delete, data: { confirm: "Do you really want to delete this user" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="family_users_new_form">
        <%= render partial: "families/family_users_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/families/_family_users_new_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :email %>

    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>

    <%= f.text_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :first_name %>

    <%= f.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>

    <%= f.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :user_type_id %>

    <%= f.collection_select :user_type_id, UserType.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :family_id, value: @family.id %>

  <div class="form-group">
    <%= f.label :phone_number %>

    <%= f.text_field :phone_number, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :dietary_restrictions %>
    <%= f.text_area :dietary_restrictions, rows: "3", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :headshot %>

    <%= f.text_field :headshot, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :walkup_song %>

    <%= f.text_field :walkup_song, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :adventure_score %>

    <%= f.text_field :adventure_score, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :nightlife_score %>

    <%= f.text_field :nightlife_score, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :beachwater_score %>

    <%= f.text_field :beachwater_score, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :freetime_score %>

    <%= f.text_field :freetime_score, class: "form-control" %>
  </div>

  <%= f.submit "Create user", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/families/_form.html.erb
<% was_validated = family.errors.any? %>

<%= form_with(model: family, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = family.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% family.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% crest_class = "form-control" %>
    <% crest_was_invalid = family.errors.include?(:crest) %>

    <% if was_validated %>
      <% if crest_was_invalid %>
        <% crest_class << " is-invalid" %>
      <% else %>
        <% crest_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :crest %>
    <%= f.file_field :crest, class: "form-control" %>
    <% if crest_was_invalid %>
      <% family.errors.full_messages_for(:crest).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% motto_class = "form-control" %>
    <% motto_was_invalid = family.errors.include?(:motto) %>

    <% if was_validated %>
      <% if motto_was_invalid %>
        <% motto_class << " is-invalid" %>
      <% else %>
        <% motto_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :motto %>
    <%= f.text_area :motto, class: motto_class, placeholder: "Enter motto" %>
    <% if motto_was_invalid %>
      <% family.errors.full_messages_for(:motto).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/families/_list_item.html.erb
<%= link_to family, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= family %>
    <small class="text-muted">
      <%= time_ago_in_words(family.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/families/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Family #<%= @family.id %>
      </h2>

      <div class="card-body">
        <%= render "form", family: @family %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/families/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Families

      <%= link_to new_family_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "families/families_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Families

        <%= link_to new_family_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @families, partial: "list_item", as: :family %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @families, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/families/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Family
      </h2>

      <div class="card-body">
        <%= render "form", family: @family %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/families/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @family, partial: "card", as: :family %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "families/family_scores" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "families/family_users" %>
  </div>
</div>